
############################################################################################################################################
############################################### Load/Install Packages ######################################################################
############################################################################################################################################

# Load or install packages to your home directory
LIBLOC<-"/home/c.c2015805/R-Rstudio/x86_64-pc-linux-gnu-library/4.2"
.libPaths(LIBLOC)

############################################################################################################################
######## from here check that everything has loaded and if not select what is missing in the Packages list manually ######## 
############################################################################################################################

BiocManager::install("MAST",lib=LIBLOC)
library(MAST,lib.loc=LIBLOC)

install.packages('metap',lib=LIBLOC)
library(metap,lib.loc=LIBLOC)

install.packages('future',lib=LIBLOC)
library(future,lib=LIBLOC)

install.packages('SCpubr',lib=LIBLOC)
library(SCpubr,lib=LIBLOC)

library(AUCell,lib.loc=LIBLOC)
library(batchelor,lib.loc=LIBLOC)
library(BiocGenerics,lib.loc=LIBLOC)
library(BiocManager,lib.loc=LIBLOC)
library(biomaRt,lib.loc=LIBLOC)
library(Cairo,lib.loc=LIBLOC)
library(cli,lib.loc=LIBLOC)
library(ComplexHeatmap,lib.loc=LIBLOC)
library(corrplot,lib.loc=LIBLOC)
library(cowplot,lib.loc=LIBLOC)
library(data.table,lib.loc=LIBLOC)
library(DelayedArray,lib.loc=LIBLOC)
library(DelayedMatrixStats,lib.loc=LIBLOC)
library(DESeq2,lib.loc=LIBLOC)
library(devtools,lib.loc=LIBLOC)
library(doMC,lib.loc=LIBLOC)
library(doRNG,lib.loc=LIBLOC)
library(dplyr,lib.loc=LIBLOC)
library(DT,lib.loc=LIBLOC)
library(edgeR,lib.loc=LIBLOC)
library(GENIE3,lib.loc=LIBLOC)
library(GGally,lib.loc=LIBLOC)
library(ggnetwork,lib.loc=LIBLOC)
library(ggplot2,lib.loc=LIBLOC)
library(ggpubr,lib.loc=LIBLOC)
library(ggrastr,lib.loc=LIBLOC)
library(ggrepel,lib.loc=LIBLOC)
library(ggthemes,lib.loc=LIBLOC)
library(glmGamPoi,lib.loc=LIBLOC) 
library(harmony,lib.loc=LIBLOC)
library(HDF5Array,lib.loc=LIBLOC)
library(hdf5r,lib.loc=LIBLOC)
library(Hmisc,lib.loc=LIBLOC)
library(hypeR,lib.loc=LIBLOC)
library(leidenbase,lib.loc=LIBLOC)
library(lifecycle,lib.loc=LIBLOC)
library(limma,lib.loc=LIBLOC)
library(lme4,lib.loc=LIBLOC)
library(Matrix,lib.loc=LIBLOC)
library(Matrix.utils,lib.loc=LIBLOC) 
library(matrixStats,lib.loc=LIBLOC)
library(mixtools,lib.loc=LIBLOC)
library(monocle,lib.loc=LIBLOC)
library(monocle3,lib.loc=LIBLOC) 
library(multtest,lib.loc=LIBLOC)
library(Nebulosa,lib.loc=LIBLOC)
library(network,lib.loc=LIBLOC)
library(NMF,lib.loc=LIBLOC)
library(openxlsx,lib.loc=LIBLOC)
library(parallel,lib.loc=LIBLOC)
library(patchwork,lib.loc=LIBLOC)
library(pcaMethods,lib.loc=LIBLOC)
library(plyr,lib.loc=LIBLOC)
library(R.utils,lib.loc=LIBLOC)
library(R2HTML,lib.loc=LIBLOC)
library(rbokeh,lib.loc=LIBLOC)
library(RcisTarget,lib.loc=LIBLOC)
library(RColorBrewer,lib.loc=LIBLOC) 
library(Rcpp,lib.loc=LIBLOC)
library(remotes,lib.loc=LIBLOC)
library(reshape2,lib.loc=LIBLOC)
library(rlang,lib.loc=LIBLOC)
library(rlist,lib.loc=LIBLOC)
library(Rtsne,lib.loc=LIBLOC)
library(S4Vectors,lib.loc=LIBLOC)
library(scater,lib.loc=LIBLOC)
library(SCENIC,lib.loc=LIBLOC)
library(scmap,lib.loc=LIBLOC)
library(SCopeLoomR,lib.loc=LIBLOC)
library(sctransform,lib.loc=LIBLOC)
library(Seurat,lib.loc=LIBLOC)
library(SeuratData,lib.loc=LIBLOC)
library(SeuratDisk,lib.loc=LIBLOC)
library(SeuratWrappers,lib.loc=LIBLOC) # no
library(SingleCellExperiment,lib.loc=LIBLOC)
library(stringr,lib.loc=LIBLOC)
library(SummarizedExperiment,lib.loc=LIBLOC)
library(terra,lib.loc=LIBLOC)
library(tibble,lib.loc=LIBLOC) 
library(tidygraph,lib.loc=LIBLOC)
library(tidyr,lib.loc=LIBLOC)
### library(tximeta,lib.loc=LIBLOC) could not install 
library(tximport,lib.loc=LIBLOC)
library(velocyto.R,lib.loc=LIBLOC)
library(zoo,lib.loc=LIBLOC)

library(scCustomize,lib.loc=LIBLOC) 
library(scales,lib.loc=LIBLOC)
library(ggalluvial,lib.loc=LIBLOC)

